language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - tip

services:
 - mysql
 - postgres
 - sqlite3

before_script:
 - mysql -e "CREATE DATABASE nisqltest;"
 - mysql -u root -e "GRANT ALL ON nisqltest.* TO nisqltest@localhost IDENTIFIED BY 'nisqltest'"
 - psql -c "CREATE DATABASE nisqltest;" -U postgres
 - psql -c "CREATE USER "nisqltest" WITH SUPERUSER PASSWORD 'nisqltest';" -U postgres
 - go get github.com/lib/pq
 - go get github.com/mattn/go-sqlite3
 - go get github.com/go-sql-driver/mysql

script: ./test_all.sh
